FROM php:7.4-cli

RUN apt update && apt install libzip-dev git -y --no-install-recommends && docker-php-ext-install -j$(nproc) pcntl pdo pdo_mysql zip pcntl

WORKDIR /var/www

COPY . /var/www

RUN php bin/console cache:clear

CMD php bin/console server:run 0.0.0.0:80